#! /bin/bash

# Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
# Description: This shell script is used to apply patches for the project
# Author: zhangyu235@huawei.com
# Create: 2019-05-17

set -ex

pkg=containerd-1.6.21
cwd=$PWD
src=$cwd/$pkg

unzip v1.6.21.zip
if [[ ! -d patch ]]; then
    tar zxf patch.tar.gz
fi

cd $src
git init
git add .
git config user.name 'build'
git config user.email 'build@obs.com'
git commit -m 'init build'
cd $cwd

series=$cwd/series.conf
while IPF= read -r line
do
	if [[ "$line" =~ ^patch* ]]; then
		echo git apply $cwd/$line
		cd $src && git apply $cwd/$line
	fi
done <"$series"
cd $cwd
cp -rf $src/* .
mv $src/.git $cwd/.git
rm -rf containerd-1.6.21
