#! /bin/bash

# Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
# Description: This shell script is used to apply patches for the project
# Author: zhangyu235@huawei.com
# Create: 2019-05-17

set -ex

pkg=containerd-1.6.20
cwd=$PWD
src=$cwd/$pkg

unzip v1.6.20.zip

cd $src
git init
git add .
git config user.name 'build'
git config user.email 'build@obs.com'
git commit -m 'init build'
cd $cwd

cp -rf $src/* .
mv $src/.git $src/git
rm -rf containerd-1.6.18
